version: "3.9"
services:
  shelternet_db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
  shelternet-service:
    image: shelternet-service
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: postgres
    depends_on:
      - shelternet_db
